"""initial baseline

Revision ID: d11ebce71a1d
Revises:
Create Date: 2026-08-12 00:03:08.708903

"""

from collections.abc import Sequence

revision: str = "d11ebce71a1d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
